# Generated by Django 4.1.7 on 2023-02-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_photographs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographs',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
