# Generated by Django 4.1.7 on 2023-02-20 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0003_photographs_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographs',
            name='date_photo',
            field=models.DateField(default=datetime.datetime(2023, 2, 20, 17, 5, 30, 363030)),
        ),
    ]
