# Generated by Django 4.1.7 on 2023-02-20 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0004_photographs_date_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographs',
            name='date_photo',
            field=models.DateField(default=datetime.datetime(2023, 2, 20, 19, 27, 13, 269291)),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
