# Generated by Django 4.1.7 on 2023-03-24 14:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galery', '0005_alter_photographs_date_photo_alter_photographs_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='date_photo',
            field=models.DateField(default=datetime.datetime(2023, 3, 24, 11, 48, 38, 667562)),
        ),
    ]
